"""CLI entry point for the coverage scoring tool."""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from pathlib import Path
from typing import TYPE_CHECKING


def _get_base_dir() -> Path:
    """Get the effective base directory, preferring RECON_FOUNDRY_ROOT env var."""
    foundry_root = os.environ.get('RECON_FOUNDRY_ROOT')
    if foundry_root:
        return Path(foundry_root)
    return Path.cwd()

if TYPE_CHECKING:
    from slither import Slither


def load_cyclomatic_complexity(complexity_file: Path) -> dict[str, dict[str, int]]:
    """Load cyclomatic complexity data from Slither API extraction.

    Expected format (generated by extract_complexity_using_slither):
    {
      "ContractName": {
        "functionName": complexity_int,
        ...
      },
      ...
    }

    Args:
        complexity_file: Path to the cyclomatic-complexity.json file.

    Returns:
        Dict mapping contract names to dicts of function names to complexity scores.
        Format: {contract_name: {function_name: complexity}}
    """
    with open(complexity_file) as f:
        data = json.load(f)

    # Data should already be in the correct format from our extraction
    return data


def extract_complexity_using_slither(project_path: Path) -> dict[str, dict[str, int]]:
    """Extract cyclomatic complexity using Slither's Python API.

    Args:
        project_path: Path to the project root directory.

    Returns:
        Dict mapping contract names to function complexities.
    """
    try:
        from slither import Slither
        from slither.utils.code_complexity import compute_cyclomatic_complexity
    except ImportError:
        print("Error: Slither is not installed. Install with: pip install slither-analyzer", file=sys.stderr)
        sys.exit(1)

    print(f"Analyzing project with Slither...", file=sys.stderr)

    # Initialize Slither
    try:
        slither = Slither(str(project_path))
    except Exception as e:
        print(f"Error: Failed to analyze project with Slither: {e}", file=sys.stderr)
        sys.exit(1)

    result = {}

    # Iterate through all contracts
    for contract in slither.contracts:
        contract_data = {}

        # Get all functions in the contract
        for function in contract.functions:
            try:
                complexity = compute_cyclomatic_complexity(function)
                contract_data[function.name] = complexity
            except Exception as e:
                print(f"Warning: Could not compute complexity for {contract.name}.{function.name}: {e}", file=sys.stderr)
                continue

        if contract_data:
            result[contract.name] = contract_data

    print(f"Extracted complexity data for {len(result)} contracts", file=sys.stderr)
    return result


def add_complexity_and_sort(
    missing_coverage_file: Path,
    complexity_data: dict[str, dict[str, int]],
) -> dict | list[dict]:
    """Add complexity scores to functions and sort by complexity.

    Args:
        missing_coverage_file: Path to the functions-missing-covg-{timestamp}.json file.
        complexity_data: Dict mapping contract names to function complexities.

    Returns:
        The full JSON structure with sorted functions (either dict with metadata or list).
    """
    with open(missing_coverage_file) as f:
        data = json.load(f)

    # Check if this is the new format with metadata
    if isinstance(data, dict) and "missing_coverage" in data:
        # New format: extract the function list from missing_coverage key
        functions = data["missing_coverage"]
        has_metadata = True
    else:
        # Old format: data is directly the function list
        functions = data
        has_metadata = False

    # Add complexity to each function
    for func_entry in functions:
        contract_name = func_entry.get("contract")
        function_name = func_entry.get("function")

        complexity = None
        if contract_name and function_name:
            # Look up complexity in the complexity_data
            if contract_name in complexity_data:
                complexity = complexity_data[contract_name].get(function_name)

        # Add complexity field (None if not found)
        func_entry["complexity"] = complexity

    # Sort by complexity (highest first), placing None values at the end
    sorted_functions = sorted(
        functions,
        key=lambda x: (x["complexity"] is None, -(x["complexity"] or 0)),
    )

    # Return the appropriate format
    if has_metadata:
        # Preserve the metadata structure
        data["missing_coverage"] = sorted_functions
        return data
    else:
        return sorted_functions


def find_latest_missing_coverage_file(magic_dir: Path) -> Path:
    """Find the most recent functions-missing-covg-{timestamp}.json file.

    Args:
        magic_dir: Path to the magic directory.

    Returns:
        Path to the most recent missing coverage file.

    Raises:
        FileNotFoundError: If no matching files are found.
    """
    pattern = re.compile(r"functions-missing-covg-(\d+)\.json$")
    matching_files: list[tuple[int, Path]] = []

    for file_path in magic_dir.glob("functions-missing-covg-*.json"):
        match = pattern.search(file_path.name)
        if match:
            timestamp = int(match.group(1))
            matching_files.append((timestamp, file_path))

    if not matching_files:
        raise FileNotFoundError(
            f"No functions-missing-covg-*.json files found in {magic_dir}"
        )

    # Sort by timestamp descending and return the most recent
    matching_files.sort(key=lambda x: x[0], reverse=True)
    return matching_files[0][1]


def main() -> int:
    """Main entry point for the CLI."""
    parser = argparse.ArgumentParser(
        description="Add cyclomatic complexity scores to coverage analysis and sort by complexity",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Example usage:
  covg-scoring

This will:
  1. Look for magic/ directory in the current working directory
  2. Find the most recent functions-missing-covg-{timestamp}.json file in magic/
  3. Read the cyclomatic-complexity.json file from magic/
  4. Add complexity scores to each function
  5. Sort functions by complexity (highest first)
  6. Overwrite the original file with the sorted, annotated data
        """,
    )
    parser.add_argument(
        "-v", "--verbose",
        action="store_true",
        help="Enable verbose output",
    )
    parser.add_argument(
        "--return-json",
        action="store_true",
        help="Return JSON output to stdout instead of writing to file",
    )

    args = parser.parse_args()

    verbose: bool = args.verbose
    return_json: bool = args.return_json

    # Find magic directory in current working directory
    magic_dir = _get_base_dir() / "magic"
    if not magic_dir.is_dir():
        print(f"Error: Magic directory not found: {magic_dir}", file=sys.stderr)
        print("Expected to find 'magic/' directory in current working directory", file=sys.stderr)
        return 1

    # Find the cyclomatic complexity file
    complexity_file = magic_dir / "cyclomatic-complexity.json"

    # Determine output stream for verbose messages
    verbose_out = sys.stderr if return_json else sys.stdout

    # Load or generate cyclomatic complexity data
    if complexity_file.is_file():
        if verbose:
            print(f"Loading cyclomatic complexity data from: {complexity_file}", file=verbose_out)
        complexity_data = load_cyclomatic_complexity(complexity_file)
    else:
        if verbose:
            print(f"Complexity file not found, generating using Slither...", file=verbose_out)

        # Generate complexity data using Slither
        project_root = _get_base_dir()
        complexity_data = extract_complexity_using_slither(project_root)

        # Save the generated data
        with open(complexity_file, 'w') as f:
            json.dump(complexity_data, f, indent=2)

        if verbose:
            print(f"Saved complexity data to: {complexity_file}", file=verbose_out)

    # Find the most recent missing coverage file
    try:
        missing_coverage_file = find_latest_missing_coverage_file(magic_dir)
    except FileNotFoundError as e:
        print(f"Error: {e}", file=sys.stderr)
        return 1

    if verbose:
        print(f"Found missing coverage file: {missing_coverage_file}", file=verbose_out)

    if verbose:
        total_functions = sum(len(funcs) for funcs in complexity_data.values())
        print(f"Loaded complexity data for {len(complexity_data)} contracts ({total_functions} functions)", file=verbose_out)

    # Process and sort functions
    if verbose:
        print(f"Processing missing coverage file: {missing_coverage_file}", file=verbose_out)

    result = add_complexity_and_sort(missing_coverage_file, complexity_data)

    # Extract function list for statistics (handle both formats)
    if isinstance(result, dict) and "missing_coverage" in result:
        function_list = result["missing_coverage"]
    else:
        function_list = result

    # Count statistics
    functions_with_complexity = sum(1 for f in function_list if f["complexity"] is not None)
    functions_without_complexity = len(function_list) - functions_with_complexity

    if verbose:
        print(f"Processed {len(function_list)} function entries", file=verbose_out)
        print(f"  - {functions_with_complexity} with complexity scores", file=verbose_out)
        print(f"  - {functions_without_complexity} without complexity scores", file=verbose_out)

    # Return JSON or write to file
    if return_json:
        print(json.dumps(result, indent=2))
        return 0
    else:
        # Write back to the same file
        with open(missing_coverage_file, "w") as f:
            json.dump(result, f, indent=2)

        print(f"Updated {missing_coverage_file} with complexity scores (sorted by complexity)")

        if verbose and function_list:
            print("\nTop 5 most complex functions:")
            for i, func in enumerate(function_list[:5]):
                if func["complexity"] is not None:
                    print(f"  {i+1}. {func['contract']}.{func['function']} (complexity: {func['complexity']})")
                else:
                    print(f"  {i+1}. {func['contract']}.{func['function']} (complexity: N/A)")

        return 0


if __name__ == "__main__":
    sys.exit(main())
