#!/usr/bin/env bash
#
# recon-magic preflight: install the bundled CLI tools and report external dependencies.
#
# The 11 bundled tools are self-contained stdlib Python scripts. We install them as thin
# PATH wrappers (no build backend, no requires-python gate, no third-party deps) so the
# fuzzing/coverage/setup workflows' PROGRAM steps can call them by name. Re-run any time;
# it is idempotent. Nothing here is fatal — `audit` and other LLM-only workflows need none
# of the external fuzzing tools.
#
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
FRAMEWORK="$SKILL_DIR/framework"
BIN_DIR="${RECON_MAGIC_BIN:-$HOME/.local/bin}"

# Pick a python
PY="$(command -v python3 || command -v python || true)"
if [ -z "$PY" ]; then
  echo "ERROR: python3 not found — the bundled tools need a Python interpreter." >&2
  exit 1
fi

echo "recon-magic preflight"
echo "  skill:     $SKILL_DIR"
echo "  framework: $FRAMEWORK"
echo "  python:    $PY ($("$PY" --version 2>&1))"
echo "  bin dir:   $BIN_DIR"
echo

# ---- Install the 11 bundled tools as wrappers ------------------------------------------
mkdir -p "$BIN_DIR"

# tool-name -> path (relative to framework/) of the entrypoint script
TOOLS="
extract-target-functions=tools/targeted_functions/extract_target_functions.py
filter-build-info=tools/filter_build_info/filter_build_info.py
order-prerequisite-func=tools/order_prerequisite_func/order_prerequisite_func.py
touched-function-identifier=tools/touched_function_identifier/touched_function_identifier.py
covg-eval=tools/covg_eval/covg_eval.py
covg-scoring=tools/covg_scoring/covg_scoring.py
get-latest-coverage=tools/get_latest_coverage/get_latest_coverage.py
save-echidna-logs=tools/save_echidna_logs/save_echidna_logs.py
merge-paths-prerequisites=tools/merge_paths_prerequisites/merge_paths_prerequisites.py
analyze-echidna-output=tools/analyze_echidna_output/analyze_echidna_output.py
update-coverage-groups=tools/update_coverage_groups/update_coverage_groups.py
"

echo "Installing bundled tools into $BIN_DIR:"
installed=0
for entry in $TOOLS; do
  name="${entry%%=*}"
  rel="${entry#*=}"
  target="$FRAMEWORK/$rel"
  wrapper="$BIN_DIR/$name"
  if [ ! -f "$target" ]; then
    echo "  ✗ $name — source missing: $target"
    continue
  fi
  cat > "$wrapper" <<EOF
#!/usr/bin/env bash
# Auto-generated by recon-magic preflight. Wraps a bundled tool.
exec "$PY" "$target" "\$@"
EOF
  chmod +x "$wrapper"
  echo "  ✓ $name"
  installed=$((installed + 1))
done
echo "Installed $installed/11 tools."
echo

# PATH check
case ":$PATH:" in
  *":$BIN_DIR:"*) : ;;
  *) echo "NOTE: $BIN_DIR is not on your PATH. Add it:"
     echo "      export PATH=\"$BIN_DIR:\$PATH\""
     echo ;;
esac

# ---- Report external dependencies ------------------------------------------------------
echo "External dependencies (needed by fuzzing/setup/coverage workflows):"
check() {
  local cmd="$1" why="$2"
  if command -v "$cmd" >/dev/null 2>&1; then
    printf "  ✓ %-14s %s\n" "$cmd" "$(command -v "$cmd")"
  else
    printf "  ✗ %-14s MISSING — %s\n" "$cmd" "$why"
  fi
}
check forge   "Foundry — https://getfoundry.sh"
check echidna "crytic/echidna — property & coverage fuzzer"
check medusa  "crytic/medusa — alt coverage fuzzer"
check sol-expand "Recon sol-expand — coverage context extraction (install separately)"
check node    "Node.js — for 'npx recon-generate'"
check npx     "comes with Node.js"
check jq      "apt/brew install jq — setup steps parse magic/*.json"
check uv      "astral-sh/uv — optional; only if installing tools as packages instead"
echo
echo "Preflight done. Missing fuzzing tools only matter for fuzzing workflows (not 'audit')."
